version: 1

update_configs:

  - package_manager: "terraform"
    directory: "/"
    update_schedule: "daily"

  - package_manager: "terraform"
    directory: "/tests/create_route53_subzone"
    update_schedule: "daily"

  - package_manager: "terraform"
    directory: "/tests/create_route53_query_log"
    update_schedule: "daily"

  - package_manager: "terraform"
    directory: "/tests/create_false"
    update_schedule: "daily"

  - package_manager: "go:modules"
    directory: "/tests"
    update_schedule: "daily"
