name: Update terraform dependencies

on:
  schedule:
    - cron:  '0 6 * * *'

jobs:
  dependabot-terraform:
    runs-on: ubuntu-latest
    steps:
      - name: update terraform dependencies
        uses: plus3it/dependabot-terraform-action@p3-implementation
        with:
          github_dependency_token: ${{ secrets.GH_READONLY_TOKEN }}
          directory: |
            /tests/create_main_subzone_query_log_kms/prereq
            /tests/create_main_zone_query_log_kms/prereq
            /tests/create_module_query_log_kms/prereq
